### ISSUE TITLE
Thermostat temperature rounded by 0.5

### ISSUE THREAD

**Issue by armand-w** [andrei-tatar/node-red-contrib-smartnora#13]
Thank you for the excellent work on the new Smart NORA, it works great!

I noticed the thermostat node rounds the ambient temperature by half a degree. So if the input of temperature is "19.3" the value in Google home is rounded to "19.5". It would be nice if the temperature value can have a higher resolution of 0.1 degree.

**Comment by andrei-tatar** [comment]
It does round it to .5 deg C on the setpoint. That's because the Google Home UI rounds it to .5 so there's no point in keeping a higher accuracy.  (I think it rounds to 0 decimal places for deg F but not sure)
It also rounds to .1 deg on the current ambient temperature.

The rounding is done client side (in the node plugin). You can try and change the code to skip the rounding but the result will be the same in the Google Home app.

**Comment by armand-w** [comment]
I didn't know Google Home UI also rounds the ambient temp to .5 deg. No point to change it then. Thank you!
