### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by yvh65** [andrei-tatar/node-red-contrib-smartnora#154]
"nora: Error: Service database is not available".

My user id is: eO43QH4HjBWbGmnvkcTwp7YQ6fB3

**Comment by andrei-tatar** [comment]
@yvh65 Can you provide more details? The complete log?
Was this something transient?

**Comment by yvh65** [comment]
30 Jan 16:21:34 - [info] nora: authenticated, uid: eO43QH4HjBWbGmnvkcTwp7YQ6fB3
30 Jan 16:21:34 - [error] nora: Error: Service database is not available
30 Jan 16:21:34 - [warn] nora: trying again in 83.5 sec

**Comment by andrei-tatar** [comment]
@yvh65 interesting, I've never seen this before. What version of `node.js` are you running?

**Comment by yvh65** [comment]
node version
v12.22.5

**Comment by yvh65** [comment]
Removed. Reinstalled. Same problem.

**Comment by andrei-tatar** [comment]
@yvh65 what node-red version? And what hardware are you running on?

**Comment by yvh65** [comment]
nr 2.2.0 docker debian 11

**Comment by yvh65** [comment]
z8350 mini pc

**Comment by andrei-tatar** [comment]
@yvh65 looking through the firebase code it seems this happens when the firebase database provider is not found so I can only think of corrupt npm install (or some dependencies didn't install correctly). Do you have the log output from the installation? Or can you try manually installing `npm install node-red-contrib-smartnora` in your `.node-red` folder?
