### ISSUE TITLE
Request: Charger

### ISSUE THREAD

**Issue by BugBasher28** [andrei-tatar/node-red-contrib-smartnora#160]
I'd like to integrate my EV Charger. Could you add support for EnergyStorage Trait/Charger device?

**Comment by andrei-tatar** [comment]
Sure, I can look into it this week.

**Comment by BugBasher28** [comment]
This feature is not yet in the master branch, right? I'm only using Node Red in Home Assistant and do not have the skills to add a different branch to Node Red...

**Comment by andrei-tatar** [comment]
@BugBasher28 no, it's not yet deployed. I've ran into an issue with the new trait. When I ask assistant to start charging, it says something is wrong, so I'm still investigating.

**Comment by andrei-tatar** [comment]
@BugBasher28 published `v1.10.0` with support for the charger device. I didn't update the docs yet. The `msg.payload` has the same format as the [energy storage trait state](https://developers.google.com/assistant/smarthome/traits/energystorage#device-states).

I noticed something weird:
If the device is unplugged (`isPluggedIn` set to `false` on the state - the default value) and you ask Google Assistant to start charging, NORA returns a `deviceUnplugged` error to Google as described in the [error codes](https://developers.google.com/assistant/smarthome/traits/energystorage#device-errors), however Google responds with `Something went wrong` instead of something like `The device is unplugged`.
