### ISSUE TITLE
Error no SYNC

### ISSUE THREAD

**Issue by Askeshine** [andrei-tatar/node-red-contrib-smartnora#175]
Hello not SYNC state of switchs / ligths...

Nora -> https://escuderokevin.ar/capturas/firefox_tmT752dLRh.png
Node Red -> https://escuderokevin.ar/capturas/firefox_f4ZK15Z4sT.png
Android APP ->https://escuderokevin.ar/capturas/firefox_utbWDeZA2f.png

Need Help

**Comment by andrei-tatar** [comment]
@Askeshine can you give more details? It's hard to understand the problem. 
So in Nora dashboard, you can see the `garaje` light is on and the `luces` light is off.
Not sure what you are showing in the Node-red image, since that is not node-red (maybe node-red dashboard?).
In Google Home, you can see you have 2 devices grouped (so if one is on, it will show both as on). 
![image](https://user-images.githubusercontent.com/6473183/164386461-1dcd86f4-edbc-4631-aac4-1818df4f6f6a.png)

**Comment by Askeshine** [comment]
@andrei-tatar 

Hello, thx for response sorry about my english.

im fixed my node red its hosted on Home Assistant.

Error for other users , need check this options https://escuderokevin.ar/capturas/firefox_abdFJ691S2.png

Thx <3

**Comment by andrei-tatar** [comment]
> Hello, thx for response sorry about my english.

No worries. It's not my native language either. You can use your native language and get Google Translate to do the rest of the job :)

So did you manage to find and solve your issue?

**Comment by Askeshine** [comment]
Yep, i resolve the issue.
