### ISSUE TITLE
Notz possible to log in with Google Home

### ISSUE THREAD

**Issue by whabby** [andrei-tatar/node-red-contrib-smartnora#244]
Hi
Since yesterday, Smart Nora devices stopped working. In Google Home, the service was away. Tried to install again, but it is not possible to sign in with Google to my account. On desktop-pc, login to smart-nora.eu works. What could be wrong? 

Regards

My user id is: age3mXh5h5Yj9J036kHSjYRAK5U2

**Comment by andrei-tatar** [comment]
Hi @whabby,
It seems like you have no devices synced in NORA. Anything relevant in the node-red logs?

**Comment by whabby** [comment]
Hi Andrei
Deleted nora-config now and tried to make new config-node. "Sign in with Google" is not working, always returns to the same "Sign in"-Screen

**Comment by andrei-tatar** [comment]
@whabby What browser are you using?
Your account is not blocked. No accounts are blocked.

**Comment by whabby** [comment]
I use Mozilla Firefox. Now I did it with Edge and it works. No Idea, why it was not working with Firefox. I will check it. Thanks for your idea!

**Comment by andrei-tatar** [comment]
Ah, interesting. I admit I haven't tested the flow with Firefox. Will look into it.

**Comment by andrei-tatar** [comment]
It seems Firefox added some security checks in place to prevent tracking between origins (nice, I think I will switch from Chrome as well). They also added a temporary exception for the firebase domains (eg: *.firebaseapp.com) until firebase catches up and stops relying on the session storage for logging in.

Nora is affected because it's using a custom domain on top of that.

I added a temporary fix to redirect to `nora-firebase.firebaseapp.com` on any browser that is not Chrome.

Pushed a fix for the firefox login in the latest package version `1.18.1`.
@whabby Let me know if this fixes it for you
