### ISSUE TITLE
Custom commands and responses

### ISSUE THREAD

**Issue by WoodyLetsCode** [andrei-tatar/node-red-contrib-smartnora#25]
Hi,
can you add support for custom conversational actions?
I saw that it should be possible by using [Google Assistant’s voice API](https://developers.google.com/assistant/conversational/overview).
It would be great to have your own voice commands and Google Assistant and returns the corresponding response.
What do you think?

**Comment by andrei-tatar** [comment]
@WoodyLetsCode there's no plan for it in the near future. This project only supports the smarthome action for now https://developers.google.com/assistant/smarthome/develop/create

However it might be interesting to add, though I'm not sure how easy it is to certify and publish something like this (if even possible).

**Comment by JaspervanKol** [comment]
A few days ago I was thinking about the same thing. A node where you can use a string as input and then your selected Google device would say what is inside the string.

I think this would be really nice to have so you can make announcements trough out your home when something happens.

**Comment by WoodyLetsCode** [comment]
Do you know any other way to do this?
I searched for other Node-RED modules, but I haven't found anything.
I tried IFTTT, but there you can only set a fixed answer and no interactive answers.
For example, I want to ask "What is the current power consumption?" and then it should return the value it gets from my outlet.

**Comment by andrei-tatar** [comment]
You can try this one: https://flows.nodered.org/node/node-red-contrib-google-action

**Comment by JaspervanKol** [comment]
@WoodyLetsCode I don't know how to do that.
I think you want an input node as trigger when you ask something to google and an output as return where you can use a string with the text and data you want.

The node that @andrei-tatar send is what you want (I think).
Could you @WoodyLetsCode look in to this if it works?

**Comment by andrei-tatar** [comment]
@JaspervanKol you can try this node for your use case https://flows.nodered.org/node/node-red-contrib-cast

**Comment by WoodyLetsCode** [comment]
> 
> 
> You can try this one: https://flows.nodered.org/node/node-red-contrib-google-action

@andrei-tatar Do you use this?

The description of it says that you have to say something like "Hey Google, talk to my test app" to have access to my commands.
I'm looking for a solution like it is on IFTTT, but with interactive answers. I want to use my voice commands whenever I want and not to start an app first.

@andrei-tatar Do you know if I have to start the app first or can I always use my commands like it is on IFTTT?

> Could you @WoodyLetsCode look in to this if it works?

@JaspervanKol Because this is only what I assume when reading the description and I'm not 100% sure about this, I maybe test it on weekend.

**Comment by JaspervanKol** [comment]
> @JaspervanKol you can try this node for your use case https://flows.nodered.org/node/node-red-contrib-cast

@andrei-tatar I already looked at a few different nodes but the problem with this is that it will override the current casting media and that it is not using the Google Assistant voice but the Google translate voice.

**Comment by andrei-tatar** [comment]
>@andrei-tatar Do you use this?

@WoodyLetsCode nope, for me the smarthome action is enough for now. Maybe I'll have a look in the future.

> @andrei-tatar I already looked at a few different nodes but the problem with this is that it will override the current casting media and that it is not using the Google Assistant voice but the Google translate voice.

If you specify `en-us` as the language/locale, maybe it will use the voice you're used to. I guess you can ask over on that repo...

**Comment by crixster** [comment]
@andrei-tatar Fantastic work you've accomplished here. I can finally link google assistant to home assistant and node red. I may have a workaround for this feature request.  @WoodyLetsCode You can consider using routines on google assistant 
https://support.google.com/googlenest/answer/7029585?co=GENIE.Platform%3DAndroid&hl=en
However the catch is since google is a "racist" (lol) , you will have to change google assistant language to English (US). 
https://support.google.com/googlenest/answer/7550584?co=GENIE.Platform%3DAndroid&hl=en
Try to use only 1 language. I tried adding Japanese and it wouldn't say out the response message. It seems to only work with English (US). 

For your info, here is my setup. I have a broadlink RM4C universal remote  that transmit IR commands to my Samsung TV. This is connected to home asssistant on my rpi4. Node-red is also running on the pi.  I use smart nora switch nodes and give them appropriate names in Node-red for example "Press Enter" and i connect the output to my home assistant service that will trigger the IR command to send out to my TV
![flow1](https://user-images.githubusercontent.com/32066057/123236412-5a3b6600-d50f-11eb-8f1b-057fb2710266.PNG)
![flow 2](https://user-images.githubusercontent.com/32066057/123237191-03825c00-d510-11eb-8bd2-e97047c37e4c.PNG)
![flow 3](https://user-images.githubusercontent.com/32066057/123237203-067d4c80-d510-11eb-85b2-e7a4247a26ea.PNG)

Go to google assistant on your phone. say "Set up routines" and go to routines settings. Create a new routine. Click on + add starter and choose voice command. Put in anything you want to say and click on done. Next click on + add action and click on adjust home devices and then click on the right chevron of adjust lights, plugs and more to pull out a list of connected devices in google home. Assuming google home can detect the node "Press Enter" that was created earlier, you should be able to see it in the list here.  Set the device to Turn On. and then click done. To add a custom response, add another action and select communicate and announce. Click on the right chevron of say something and type out your response. Then click on done until you can click on save to save the routine. For my case, whenever i say "Press Enter", it will turn on the smart nora switch node which will turn on the home assistant node that sends the command out to my TV. Finally i can skips youtube ads by saying "Press Enter" 

"We go through extraordinary lengths to be lazy"

**Comment by andrei-tatar** [comment]
I will close this issue for now as for the near future NORA will not support conversational actions, nor voice notifications to Google Home devices.

**Comment by WoodyLetsCode** [comment]
@crixster Thank you for your detailed guide. But the problem here is I can't get "intelligent" answers. For example, I want to ask how many windows are open and get the corresponding response. As far as I know is this currently not possible. Or do you have a solution for this?

**Comment by andrei-tatar** [comment]
Not sure, as I don't have any to check, but I think Google Home supports "how many windows are open" question.
At least is supports "how many lights are on"...

**Comment by WoodyLetsCode** [comment]
Okay, maybe this was a bad example. 😆  Above I had the example with the power consumption:

> For example, I want to ask "What is the current power consumption?" and then it should return the value it gets from my outlet.

It is sad that the Google outlet device is so undeveloped.
And Google routines can only return fixed answers and no individual ones. 😞
