### ISSUE TITLE
unhandled error: HTTP response (429 Rate exceeded.)

### ISSUE THREAD

**Issue by FireWizard52** [andrei-tatar/node-red-contrib-smartnora#26]
Hi,

user id is r53vj694TYgtSWAQKsDVaCZJJgk1. 

Currently I receive the following information in the Debug pane, from Nora and I have no clue, what the root cause is.
I'm even not sure, whether this a Smart Nora or a Firebase issue. Any ideas?

> string[314]

unhandled error (trying again in 81.5 sec): HTTP response (429 Rate exceeded.)
Error: HTTP response (429 Rate exceeded.)
    at FirebaseSync.doHttpCall (/home/pi/.node-red/node_modules/node-red-contrib-smartnora/build/firebase/sync.js:203:27)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)

**Comment by andrei-tatar** [comment]
That's a weird one. I'll check the logs.

**Comment by andrei-tatar** [comment]
ok, checking the logs revealed a weird issue. It seems that everyone disconnected from firebase at around the same time (probably some Google maintenance thing) and everyone connected back at the exact same time, flooding the backend with sync requests.

It seems to have recovered pretty quick after that.

I definitely need to spread out the 1st sync call after the connect. I wasn't aware this might happen.

**Comment by andrei-tatar** [comment]
Found a bug: after a failure, the retry doesn't really work and just shows the same error message over, and over.

**Comment by andrei-tatar** [comment]
@FireWizard52 I published v1.0.5 that addresses this issue:
https://github.com/andrei-tatar/node-red-contrib-smartnora/releases/tag/v1.0.5

Summary:
- firebase disconnected lots of users at the same time and they all connected again at the same time (few seconds later)
- some sync calls failed (the 429 status code) because of the load (some hundreds of requests in a few milliseconds) 
- the retry didn't really work prior to this fix

I will close this bug for now.
