### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by KenSpurling** [andrei-tatar/node-red-contrib-smartnora#280]
I did some updates to my Windows PC. Since then everything at my end looks fine.My Nodered to Nora looks OK. My dashboard on this site works OK.

On Google home all devices are now shown offline. When I try to unlink GH goes to "link new" saying no Nora devices found. How do I resolve this?

My user id is: LJ1yHbLNqHPXOhtFlsO8HUPS45D2

**Comment by andrei-tatar** [comment]
@KenSpurling I think all should be working for you as I don't see any issues in the DB related to your user account. 
I would recommend updating the plugin to the latest version (1.20.0) as you're running an older version (1.15.1) and lots of bugs have been solved since.

**Comment by KenSpurling** [comment]
Hi,
Yes working fine again now, and I've also updated the package as you
suggested. Thanks!

Could I have corrected the problem myself and if so how?

Best Regards,

Ken Spurling

7 Ashton Avenue
Rainhill
Prescot
Merseyside
L35 0QQ

01514309887
07746108569

***@***.***

**Comment by andrei-tatar** [comment]
NORA used to rely on the machine time to be accurate when determining which devices are online. It basically checks the time it was last updated and if the time span is within a predefined range, the device is online, otherwise it's offline. If the time was correctly set, without drift, then you shouldn't have any issues.

It might be auto fixed if the device you're running NORA on, does an NTP time update automatically after some time after node-red started.

This issue was fixed in a recent update and NORA corrects any clock drift from the server clock.

**Comment by KenSpurling** [comment]
👍
