### ISSUE TITLE
Google devices drop out of Google App - iPhone.

### ISSUE THREAD

**Issue by Howie55** [andrei-tatar/node-red-contrib-smartnora#40]
For the past three or four days I constantly have to re-discover my devices in the Google App under Smart-NORA.  Each time there is only one device as listed so I have to refresh the link in Node-Red and then when I go back into the Google App all 21 devices are back again.  I then have to go into each device and add it back into its right room.  Am I the only one having this issue.  I don't restart NodeRed I just uncheck the local execution support and then recheck it and then redeploy NodeRed.  After this all devices come back

Howard - cppIsALiNXT1c6p2QQ3SlMvrmnD3.

**Comment by andrei-tatar** [comment]
@Howie55 Are you using multiple node-red instances connected to the same account with the same "group name"?

**Comment by Howie55** [comment]
Hi, I have three copies of NodeRed running.  My main system with SmartNORA, a second one without and then I found my "play" NodeRed had a copy of SmartNora setup.  I have now deleted all references.  Appreciate your pointing me in the right direction.  I will now monitor and see what happens.  Interestingly (but not funny) was my wife got notified, on her mobile, that all devices had dropped off at 03:16 in the morning.  Not happy.  There was only one device remaining and that was the one in the "play" NodeRed.  Howard.

**Comment by andrei-tatar** [comment]
Ok, just make sure you have a unique group name on each separate instance of node-red, otherwise the devices will get overridden.

If you have extra groups that you don't use anymore but still show in Google Home, you can go to https://smart-nora.eu/my-nora and delete them (details here: https://github.com/andrei-tatar/node-red-contrib-smartnora/tree/master/doc/faq#i-have-ghost-devices-in-my-google-home-application)
