### ISSUE TITLE
Google Assistant response of thermostat node.

### ISSUE THREAD

**Issue by FireWizard52** [andrei-tatar/node-red-contrib-smartnora#51]
Hello @andrei-tatar,

I saw your comment #50 and thought, that if it is so easy to suppress a voice response in Google Assistant, would it be possible to add a response.

I have a thermostat in the living room and mode, current temperature and set-point is supported.

If I ask the Google Assistant e.g.: "What is the temperature in the Living Room" (in Dutch), the Assistant answers e.g. (in Dutch): "The thermostat is in automatic mode and the set-point has been set to 22 degrees" (Which is correct) But no response, regarding the current temperature. 

With the sensor node, you were able to suppress the useless set-point, but I wonder, is it possible to add the useful answer, regarding the temperature in the thermostat node?

Regards

**Comment by andrei-tatar** [comment]
Hey @FireWizard52 
Unfortunately I can't tell Google how to respond. The property is already in the state so it depends on Google how it formulates the answer. For the sensor it was easier since I could just remove the property from the state... I think they thought the setpoint is more useful for a Thermostat since the heating/cooling system should track the setpoint as close as possible.

I also noticed that if I ask "what is the current temperature in <room>?" it responds with the current temperature, not with the setpoint. 

Regards

**Comment by andrei-tatar** [comment]
Btw, I'll close this issue for now since it's not under NORA's control.
