### ISSUE TITLE
Feature Request: Notification icons

### ISSUE THREAD

**Issue by BugBasher28** [andrei-tatar/node-red-contrib-smartnora#52]
Would like to use Font Awesome Icons for the notifications, in the same way these icons are used in Home Assistant. (I.e. just adding _fa-smile_ will give that icon).

**Comment by andrei-tatar** [comment]
Web notifications don't support font icons, only images.
https://developer.mozilla.org/en-US/docs/Web/API/Notification/icon

In order to support `fa-smile` as an icon, the icon images would need to be hosted somewhere publicly and a mapping would need to exist inside NORA that would know to map `fa-smile` to a specific image uri: `https://some-domain.io/fa-smile.png`

I'm not to keen to strongly couple NORA to FontAwesome icons (or any other icons for that matter).

But you can create your own Github repo (or any other way of hosting a few small files), upload the icon files you want to use add add the links in the notification node. (for example, a link to an image from this repo: https://github.com/andrei-tatar/node-red-contrib-smartnora/raw/master/doc/faq/delete_group.png)

**Comment by BugBasher28** [comment]
Ok, understood.
