### ISSUE TITLE
Request: Toggle

### ISSUE THREAD

**Issue by tmichaeltx** [andrei-tatar/node-red-contrib-smartnora#57]
I find that many of the devices that I control via Hubitat or Zigbee2MQTT have the ability to accept a toggle between on/off request. I am using smartnora to both make google home one of several control dashboards. In some of the others, I have the option to toggle multiple items and would like to keep google home up to date on the status of the devices that have been toggled. To do so requires keeping track outside of my smartnora node and then sending the appropriate on/off. But since the node has the on/off state (displayed below the node), it would be nice if the light and outlet nodes had the ability to process a toggle request from the node red input.

**Comment by andrei-tatar** [comment]
I don't think that's a good idea since it might cause the devices to become out of sync. If something fails with the real device and the toggle doesn't actually change the state, nora and the real device will be out of sync.

Best thing to do is to update the nora device state each time the real device state changes.
- send toggle to real device (it handles it)
- when/if real device state changes -> update nora with the new state

For a device that doesn't support notifying state changes (it doesn't support MQTT) I'm polling the state each 5sec with an HTTP request and I update the NORA state accordingly. This way they are almost always in sync, with a max 5 sec delay

![image](https://user-images.githubusercontent.com/6473183/125919523-f39d1af7-66c9-4d9f-ad97-b099b930410c.png)

**Comment by tmichaeltx** [comment]
I agree that your solution is workable and so can understand focusing on other areas, but wouldn't complain if you changed your mind.

**Comment by normanr** [comment]
What about devices where you can't get the device state into NodeRed? eg: a TV or a Media Remote may have a power toggle button, but there's no way to detect if the device is currently on or off (short of setting up a webcam and doing image recognition).

I'm not sure if the request is to get Smart NORA to track toggles, or to include a [Toggles trait](https://developers.google.com/assistant/smarthome/traits/toggles) in the device info, but it looks like Smart Home doesn't handle devices where there's no way to get the current status. (You can turn things on and off, but if that ends up sending the same action, then things _will_ get out of sync).
