### ISSUE TITLE
Doesnt work?

### ISSUE THREAD

**Issue by realjax** [andrei-tatar/node-red-contrib-smartnora#8]
It's not really clear to me if I can actually use and test this or not??
Seems the documentation is a mix from the old NORA and the new?

I have created an account and have also installed node-red-contrib-smartnora.  I can add a light to my flows for instance but it doesn't seem to want to work with my google home app. The light doesn't show up which seems logical as I only see the 'old' nora stuff. Do I need to add something else to that app?

cheers

**Comment by andrei-tatar** [comment]
It's not yet approved by Google, meaning you need to send me the email account you're using in Google Home so I can add you as a Project member.

There is a slack group where this new version is discussed: 
https://join.slack.com/t/smart-nora/shared_invite/zt-nn2w4efp-AXE5jUimp8gzqFI9NK62Ng

**Comment by patrik-malina** [comment]
Hi, I'd like to try, but link is expired.
Sending my email to you.

Thanks, in advance.

**Comment by andrei-tatar** [comment]
Here's a new link:
https://join.slack.com/t/smart-nora/shared_invite/zt-p48h74zl-ZxopzJPGnUZKMjFDPjlVKA

**Comment by andrei-tatar** [comment]
`Smart NORA` action should now be public in Google Home.
No more special things that need to happen in order to have access!

**Comment by Chris-The-Tuner** [comment]
I reopen this since i still have this issue.
Made my account today, cinfigured nore-red smartnora and made a flow with a "garage" node.

Within node-red everything works like a charm, even notifications are possible.

BUT, the Garage Node does not show up in my Home App, Google does not even recognize the Service as linked after doing so in home app.
I can always "add new" smart nora service.
On the other hand on googles webpage i can see the service linked to my account.

I'm out of ideas.

**Comment by andrei-tatar** [comment]
@Chris-The-Tuner the garage and lock work only with 2FA pin enabled for now.
If you install the latest package you will be able to see the error message in node-red.

![image](https://user-images.githubusercontent.com/6473183/115104626-6977c380-9f62-11eb-9928-5d2ed959b30b.png)

**Comment by Chris-The-Tuner** [comment]
I installed via "manage palette" so i was thinking i'm on the newest release 🙈

**Comment by andrei-tatar** [comment]
Not sure how often the palette index is refreshed. But the latest version is `1.0.0-beta.1`...

**Comment by Chris-The-Tuner** [comment]
So Node-Red tells me i'm running 1.0.0-alpha.6.
I managed to get everything working:
Had to config smartnora twice (one with pin, one without since i want to turn on a light without a pin :P)
Works like a charm now, i'm happy that this Service is there, never used anything better !
Great work, thanks soo mutch !

**Comment by andrei-tatar** [comment]
Yes, I went with a separate config approach for 2FA. 
Maybe it will be better to move the 2FA config to each node individually.

**Comment by Chris-The-Tuner** [comment]
I would prefer the Pin setting per node, not per config.
By now i would only use Pin with Garage/Driveway Door or my main Door so having 2 - 4 configs seems easy enough  but if i would use more and more the groups would add up fast.
Setting the Pin by "device" (node) would be way simpler.
